// Code generated by testgen. DO NOT EDIT.
package day07_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc25/day07"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/07_sample.txt", day07.Part1)
		if !ok {
			return
		}
		if result != 21 {
			t.Errorf("Expected %v, got %v", 21, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/07.txt", day07.Part1)
		if !ok {
			return
		}
		if result != 1658 {
			t.Errorf("Expected %v, got %v", 1658, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/07_sample.txt", day07.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/07.txt", day07.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/07_sample.txt", day07.Part2)
		if !ok {
			return
		}
		if result != 40 {
			t.Errorf("Expected %v, got %v", 40, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/07.txt", day07.Part2)
		if !ok {
			return
		}
		if result != 53916299384254 {
			t.Errorf("Expected %v, got %v", 53916299384254, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/07_sample.txt", day07.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/07.txt", day07.Part2)
	})
}
