# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day12.part_1 import Part1
from aoc24.day12.part_2 import Part2


class Test2024Day12Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/12_sample.txt"),
                         "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/12_sample.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 1930)

    @unittest.skipUnless(os.path.exists("data/full/24/12.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/12.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 1522850)


class Test2024Day12Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/12_sample.txt"),
                         "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/12_sample.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 1206)

    @unittest.skipUnless(os.path.exists("data/full/24/12.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/12.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 953738)


if __name__ == "__main__":
    unittest.main()
