// Code generated by testgen. DO NOT EDIT.
package day14_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day14"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/14.txt", day14.Part1)
		if !ok {
			return
		}
		if result != 224554908 {
			t.Errorf("Expected %v, got %v", 224554908, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/14.txt", day14.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/14.txt", day14.Part2)
		if !ok {
			return
		}
		if result != 6644 {
			t.Errorf("Expected %v, got %v", 6644, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/14.txt", day14.Part2)
	})
}

