// Code generated by testgen. DO NOT EDIT.
package day12_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day12"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/12_sample.txt", day12.Part1)
		if !ok {
			return
		}
		if result != 1930 {
			t.Errorf("Expected %v, got %v", 1930, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/12.txt", day12.Part1)
		if !ok {
			return
		}
		if result != 1522850 {
			t.Errorf("Expected %v, got %v", 1522850, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/12_sample.txt", day12.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/12.txt", day12.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/12_sample.txt", day12.Part2)
		if !ok {
			return
		}
		if result != 1206 {
			t.Errorf("Expected %v, got %v", 1206, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/12.txt", day12.Part2)
		if !ok {
			return
		}
		if result != 953738 {
			t.Errorf("Expected %v, got %v", 953738, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/12_sample.txt", day12.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/12.txt", day12.Part2)
	})
}
