// Code generated by testgen. DO NOT EDIT.
package day07_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day07"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `32T3K 765
T55J5 684
KK677 28
KTJJT 220
QQQJA 483`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day07.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 6440 {
			t.Errorf("Expected %v, got %v", 6440, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day07.Part1(reader)
		}
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day07.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 5905 {
			t.Errorf("Expected %v, got %v", 5905, result)
		}
	})

	t.Run("sample2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/07_sample2.txt", day07.Part2)
		if !ok {
			return
		}
		if result != 9800 {
			t.Errorf("Expected %v, got %v", 9800, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day07.Part2(reader)
		}
	})

	b.Run("sample2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/07_sample2.txt", day07.Part2)
	})
}
