// Code generated by testgen. DO NOT EDIT.
package day03_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day03"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/03_sample.txt", day03.Part1)
		if !ok {
			return
		}
		if result != 4484 {
			t.Errorf("Expected %v, got %v", 4484, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/03_sample.txt", day03.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/03_sample.txt", day03.Part2)
		if !ok {
			return
		}
		if result != 467835 {
			t.Errorf("Expected %v, got %v", 467835, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/03_sample.txt", day03.Part2)
	})
}
