// Code generated by testgen. DO NOT EDIT.
package day22_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day22"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `1
10
100
2024`

var testData2 = `1
2
3
2024`

func TestPart1(t *testing.T) {
	t.Run("sample_part1", func(t *testing.T) {
		result, err := day22.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 37327623 {
			t.Errorf("Expected %v, got %v", 37327623, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/22.txt", day22.Part1)
		if !ok {
			return
		}
		if result != 14622549304 {
			t.Errorf("Expected %v, got %v", 14622549304, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample_part1", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day22.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/22.txt", day22.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_part2", func(t *testing.T) {
		result, err := day22.Part2(strings.NewReader(testData2))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 23 {
			t.Errorf("Expected %v, got %v", 23, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/22.txt", day22.Part2)
		if !ok {
			return
		}
		if result != 1735 {
			t.Errorf("Expected %v, got %v", 1735, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_part2", func(b *testing.B) {
		reader := strings.NewReader(testData2)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day22.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/22.txt", day22.Part2)
	})
}

