// Code generated by testgen. DO NOT EDIT.
package day06_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day06"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/06_sample.txt", day06.Part1)
		if !ok {
			return
		}
		if result != 41 {
			t.Errorf("Expected %v, got %v", 41, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/06.txt", day06.Part1)
		if !ok {
			return
		}
		if result != 5305 {
			t.Errorf("Expected %v, got %v", 5305, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/06_sample.txt", day06.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/06.txt", day06.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/06_sample.txt", day06.Part2)
		if !ok {
			return
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/06.txt", day06.Part2)
		if !ok {
			return
		}
		if result != 2143 {
			t.Errorf("Expected %v, got %v", 2143, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/06_sample.txt", day06.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/06.txt", day06.Part2)
	})
}
