// Code generated by testgen. DO NOT EDIT.
package day14_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day14"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/14_sample.txt", day14.Part1)
		if !ok {
			return
		}
		if result != 136 {
			t.Errorf("Expected %v, got %v", 136, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/14.txt", day14.Part1)
		if !ok {
			return
		}
		if result != 106517 {
			t.Errorf("Expected %v, got %v", 106517, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/14_sample.txt", day14.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/14.txt", day14.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/14_sample.txt", day14.Part2)
		if !ok {
			return
		}
		if result != 64 {
			t.Errorf("Expected %v, got %v", 64, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/14.txt", day14.Part2)
		if !ok {
			return
		}
		if result != 79723 {
			t.Errorf("Expected %v, got %v", 79723, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/14_sample.txt", day14.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/14.txt", day14.Part2)
	})
}
