// Code generated by testgen. DO NOT EDIT.
package day11_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day11"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `125 17`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day11.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 55312 {
			t.Errorf("Expected %v, got %v", 55312, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/11.txt", day11.Part1)
		if !ok {
			return
		}
		if result != 235850 {
			t.Errorf("Expected %v, got %v", 235850, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day11.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/11.txt", day11.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day11.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 65601038650482 {
			t.Errorf("Expected %v, got %v", 65601038650482, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/11.txt", day11.Part2)
		if !ok {
			return
		}
		if result != 279903140844645 {
			t.Errorf("Expected %v, got %v", 279903140844645, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day11.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/11.txt", day11.Part2)
	})
}
