// Code generated by testgen. DO NOT EDIT.
package day15_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day15"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample_large", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/15_sample_large.txt", day15.Part1)
		if !ok {
			return
		}
		if result != 10092 {
			t.Errorf("Expected %v, got %v", 10092, result)
		}
	})

	t.Run("sample_small", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/15_sample_small.txt", day15.Part1)
		if !ok {
			return
		}
		if result != 2028 {
			t.Errorf("Expected %v, got %v", 2028, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/15.txt", day15.Part1)
		if !ok {
			return
		}
		if result != 1430536 {
			t.Errorf("Expected %v, got %v", 1430536, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample_large", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/15_sample_large.txt", day15.Part1)
	})

	b.Run("sample_small", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/15_sample_small.txt", day15.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/15.txt", day15.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_large", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/15_sample_large.txt", day15.Part2)
		if !ok {
			return
		}
		if result != 9021 {
			t.Errorf("Expected %v, got %v", 9021, result)
		}
	})

	t.Run("sample_small", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/15_sample_small.txt", day15.Part2)
		if !ok {
			return
		}
		if result != 1751 {
			t.Errorf("Expected %v, got %v", 1751, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/15.txt", day15.Part2)
		if !ok {
			return
		}
		if result != 1452348 {
			t.Errorf("Expected %v, got %v", 1452348, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_large", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/15_sample_large.txt", day15.Part2)
	})

	b.Run("sample_small", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/15_sample_small.txt", day15.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/15.txt", day15.Part2)
	})
}

