// Code generated by testgen. DO NOT EDIT.
package day10_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day10"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `..F7.
.FJ|.
SJ.L7
|F--J
LJ...`

func TestPart1(t *testing.T) {
	t.Run("sample1", func(t *testing.T) {
		result, err := day10.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 8 {
			t.Errorf("Expected %v, got %v", 8, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/10.txt", day10.Part1)
		if !ok {
			return
		}
		if result != 6923 {
			t.Errorf("Expected %v, got %v", 6923, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample1", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day10.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/10.txt", day10.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/10_sample2.txt", day10.Part2)
		if !ok {
			return
		}
		if result != 4 {
			t.Errorf("Expected %v, got %v", 4, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/10.txt", day10.Part2)
		if !ok {
			return
		}
		if result != 529 {
			t.Errorf("Expected %v, got %v", 529, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/10_sample2.txt", day10.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/10.txt", day10.Part2)
	})
}
