# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day02.part_1 import Part1
from aoc25.day02.part_2 import Part2


class Test2025Day02Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/02_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/02_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 1227775554)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/02.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/02.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 64215794229)


class Test2025Day02Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/02_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/02_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 4174379265)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/02.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/02.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 85513235135)


if __name__ == "__main__":
    unittest.main()
