// Code generated by testgen. DO NOT EDIT.
package day17_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day17"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `111111111111
999999999991
999999999991
999999999991
999999999991`

func TestPart1(t *testing.T) {
	t.Run("sample1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/17_sample.txt", day17.Part1)
		if !ok {
			return
		}
		if result != 102 {
			t.Errorf("Expected %v, got %v", 102, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/17.txt", day17.Part1)
		if !ok {
			return
		}
		if result != 967 {
			t.Errorf("Expected %v, got %v", 967, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/17_sample.txt", day17.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/17.txt", day17.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample2", func(t *testing.T) {
		result, err := day17.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 71 {
			t.Errorf("Expected %v, got %v", 71, result)
		}
	})

	t.Run("sample1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/17_sample.txt", day17.Part2)
		if !ok {
			return
		}
		if result != 94 {
			t.Errorf("Expected %v, got %v", 94, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/17.txt", day17.Part2)
		if !ok {
			return
		}
		if result != 1101 {
			t.Errorf("Expected %v, got %v", 1101, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample2", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day17.Part2(reader)
		}
	})

	b.Run("sample1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/17_sample.txt", day17.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/17.txt", day17.Part2)
	})
}
