# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day10.part_1 import Part1
from aoc24.day10.part_2 import Part2

testData = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732"""


class Test2024Day10Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 36)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/10.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/10.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 796)


class Test2024Day10Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 81)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/10.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/10.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 1942)


if __name__ == "__main__":
    unittest.main()
