// Code generated by testgen. DO NOT EDIT.
package day06_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc25/day06"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/06_sample.txt", day06.Part1)
		if !ok {
			return
		}
		if result != 4277556 {
			t.Errorf("Expected %v, got %v", 4277556, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/06.txt", day06.Part1)
		if !ok {
			return
		}
		if result != 4583860641327 {
			t.Errorf("Expected %v, got %v", 4583860641327, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/06_sample.txt", day06.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/06.txt", day06.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/06_sample.txt", day06.Part2)
		if !ok {
			return
		}
		if result != 3263827 {
			t.Errorf("Expected %v, got %v", 3263827, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/06.txt", day06.Part2)
		if !ok {
			return
		}
		if result != 11602774058280 {
			t.Errorf("Expected %v, got %v", 11602774058280, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/06_sample.txt", day06.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/06.txt", day06.Part2)
	})
}
