// Code generated by testgen. DO NOT EDIT.
package day16_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day16"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/16_sample.txt", day16.Part1)
		if !ok {
			return
		}
		if result != 46 {
			t.Errorf("Expected %v, got %v", 46, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/16.txt", day16.Part1)
		if !ok {
			return
		}
		if result != 6906 {
			t.Errorf("Expected %v, got %v", 6906, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/16_sample.txt", day16.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/16.txt", day16.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/16_sample.txt", day16.Part2)
		if !ok {
			return
		}
		if result != 51 {
			t.Errorf("Expected %v, got %v", 51, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/16.txt", day16.Part2)
		if !ok {
			return
		}
		if result != 7330 {
			t.Errorf("Expected %v, got %v", 7330, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/16_sample.txt", day16.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/16.txt", day16.Part2)
	})
}
