// Code generated by testgen. DO NOT EDIT.
package day12_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day12"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/12_sample.txt", day12.Part1)
		if !ok {
			return
		}
		if result != 21 {
			t.Errorf("Expected %v, got %v", 21, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/12.txt", day12.Part1)
		if !ok {
			return
		}
		if result != 7622 {
			t.Errorf("Expected %v, got %v", 7622, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/12_sample.txt", day12.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/12.txt", day12.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/12_sample.txt", day12.Part2)
		if !ok {
			return
		}
		if result != 525152 {
			t.Errorf("Expected %v, got %v", 525152, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/12.txt", day12.Part2)
		if !ok {
			return
		}
		if result != 4964259839627 {
			t.Errorf("Expected %v, got %v", 4964259839627, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/12_sample.txt", day12.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/12.txt", day12.Part2)
	})
}
