// Code generated by testgen. DO NOT EDIT.

// Fallback for IDE intellisense; the real value is set by CMake.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <gtest/gtest.h>
#include <sstream>
#include <fstream>
#include <filesystem>

#include "aoc23/day05/day05.h"


TEST(Aoc23Day05Part1, sample) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/samples/23/05_sample.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc23::day05::Part1(stream), 35);
}

TEST(Aoc23Day05Part1, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/23/05.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc23::day05::Part1(stream), 261668924);
}

TEST(Aoc23Day05Part2, sample) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/samples/23/05_sample.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc23::day05::Part2(stream), 46);
}

TEST(Aoc23Day05Part2, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/23/05.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc23::day05::Part2(stream), 24261545);
}
