# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day16.part_1 import Part1
from aoc24.day16.part_2 import Part2



class Test2024Day16Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/16_sample_1.txt"), "Test data file not found")
    def test_sample_1(self):
        with open("data/samples/24/16_sample_1.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 7036)

    @unittest.skipUnless(os.path.exists("data/samples/24/16_sample_2.txt"), "Test data file not found")
    def test_sample_2(self):
        with open("data/samples/24/16_sample_2.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 11048)


class Test2024Day16Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/16_sample_1.txt"), "Test data file not found")
    def test_sample_1(self):
        with open("data/samples/24/16_sample_1.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 45)

    @unittest.skipUnless(os.path.exists("data/samples/24/16_sample_2.txt"), "Test data file not found")
    def test_sample_2(self):
        with open("data/samples/24/16_sample_2.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 64)


if __name__ == "__main__":
    unittest.main()
