# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day16.part_1 import Part1
from aoc24.day16.part_2 import Part2


class Test2024Day16Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/16_sample_1.txt")),
        "Test data file not found")
    def test_sample_1(self):
        path = resolve_data_path("data/samples/24/16_sample_1.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 7036)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/16_sample_2.txt")),
        "Test data file not found")
    def test_sample_2(self):
        path = resolve_data_path("data/samples/24/16_sample_2.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 11048)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/16.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/16.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 105508)


class Test2024Day16Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/16_sample_1.txt")),
        "Test data file not found")
    def test_sample_1(self):
        path = resolve_data_path("data/samples/24/16_sample_1.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 45)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/16_sample_2.txt")),
        "Test data file not found")
    def test_sample_2(self):
        path = resolve_data_path("data/samples/24/16_sample_2.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 64)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/16.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/16.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 548)


if __name__ == "__main__":
    unittest.main()
