// Code generated by testgen. DO NOT EDIT.
package day11_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day11"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/11_sample.txt", day11.Part1)
		if !ok {
			return
		}
		if result != 374 {
			t.Errorf("Expected %v, got %v", 374, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/11.txt", day11.Part1)
		if !ok {
			return
		}
		if result != 9686930 {
			t.Errorf("Expected %v, got %v", 9686930, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/11_sample.txt", day11.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/11.txt", day11.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/11_sample.txt", day11.Part2)
		if !ok {
			return
		}
		if result != 82000210 {
			t.Errorf("Expected %v, got %v", 82000210, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/11.txt", day11.Part2)
		if !ok {
			return
		}
		if result != 630728425490 {
			t.Errorf("Expected %v, got %v", 630728425490, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/11_sample.txt", day11.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/11.txt", day11.Part2)
	})
}
