// Code generated by testgen. DO NOT EDIT.
package day01_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day01"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `3   4
4   3
2   5
1   3
3   9
3   3`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day01.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 11 {
			t.Errorf("Expected %v, got %v", 11, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/01.txt", day01.Part1)
		if !ok {
			return
		}
		if result != 2057374 {
			t.Errorf("Expected %v, got %v", 2057374, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day01.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/01.txt", day01.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day01.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 31 {
			t.Errorf("Expected %v, got %v", 31, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/01.txt", day01.Part2)
		if !ok {
			return
		}
		if result != 23177084 {
			t.Errorf("Expected %v, got %v", 23177084, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day01.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/01.txt", day01.Part2)
	})
}

