# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day06.part_1 import Part1
from aoc24.day06.part_2 import Part2


class Test2024Day06Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/06_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/24/06_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 41)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/06.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/06.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 5305)


class Test2024Day06Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/06_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/24/06_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 6)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/06.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/06.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 2143)


if __name__ == "__main__":
    unittest.main()
