# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day05.part_1 import Part1
from aoc24.day05.part_2 import Part2


class Test2024Day05Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/05_sample.txt"),
                         "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/05_sample.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 143)

    @unittest.skipUnless(os.path.exists("data/full/24/05.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/05.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 5268)


class Test2024Day05Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/05_sample.txt"),
                         "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/05_sample.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 123)

    @unittest.skipUnless(os.path.exists("data/full/24/05.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/05.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 5799)


if __name__ == "__main__":
    unittest.main()
