// Code generated by testgen. DO NOT EDIT.
package day02_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc25/day02"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/02_sample.txt", day02.Part1)
		if !ok {
			return
		}
		if result != 1227775554 {
			t.Errorf("Expected %v, got %v", 1227775554, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/02.txt", day02.Part1)
		if !ok {
			return
		}
		if result != 64215794229 {
			t.Errorf("Expected %v, got %v", 64215794229, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/02_sample.txt", day02.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/02.txt", day02.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/02_sample.txt", day02.Part2)
		if !ok {
			return
		}
		if result != 4174379265 {
			t.Errorf("Expected %v, got %v", 4174379265, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/02.txt", day02.Part2)
		if !ok {
			return
		}
		if result != 85513235135 {
			t.Errorf("Expected %v, got %v", 85513235135, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/02_sample.txt", day02.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/02.txt", day02.Part2)
	})
}
