// Code generated by testgen. DO NOT EDIT.
package day23_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day23"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/23_sample.txt", day23.Part1)
		if !ok {
			return
		}
		if result != 7 {
			t.Errorf("Expected %v, got %v", 7, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/23.txt", day23.Part1)
		if !ok {
			return
		}
		if result != 926 {
			t.Errorf("Expected %v, got %v", 926, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/23_sample.txt", day23.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/23.txt", day23.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/23_sample.txt", day23.Part2)
		if !ok {
			return
		}
		if result != "co,de,ka,ta" {
			t.Errorf("Expected %v, got %v", "co,de,ka,ta", result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/23.txt", day23.Part2)
		if !ok {
			return
		}
		if result != "az,ed,hz,it,ld,nh,pc,td,ty,ux,wc,yg,zz" {
			t.Errorf("Expected %v, got %v", "az,ed,hz,it,ld,nh,pc,td,ty,ux,wc,yg,zz", result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/23_sample.txt", day23.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/23.txt", day23.Part2)
	})
}
