// Code generated by testgen. DO NOT EDIT.
package day06_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day06"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `Time:      7  15   30
Distance:  9  40  200`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day06.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 288 {
			t.Errorf("Expected %v, got %v", 288, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day06.Part1(reader)
		}
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day06.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 71503 {
			t.Errorf("Expected %v, got %v", 71503, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day06.Part2(reader)
		}
	})
}
