# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day09.part_1 import Part1
from aoc24.day09.part_2 import Part2

testData = """2333133121414131402"""


class Test2024Day09Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 1928)

    @unittest.skipUnless(os.path.exists("data/full/24/09.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/09.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 6435922584968)


class Test2024Day09Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 2858)

    @unittest.skipUnless(os.path.exists("data/full/24/09.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/09.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 6469636832766)


if __name__ == "__main__":
    unittest.main()
