# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day22.part_1 import Part1
from aoc24.day22.part_2 import Part2

testData = """1
10
100
2024"""
testData2 = """1
2
3
2024"""


class Test2024Day22Part01(unittest.TestCase):

    def test_sample_part1(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 37327623)

    @unittest.skipUnless(os.path.exists("data/full/24/22.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/22.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 14622549304)


class Test2024Day22Part02(unittest.TestCase):

    def test_sample_part2(self):
        with io.StringIO() as f:
            f.write(testData2)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 23)

    @unittest.skipUnless(os.path.exists("data/full/24/22.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/22.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 1735)


if __name__ == "__main__":
    unittest.main()
