# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day15.part_1 import Part1
from aoc24.day15.part_2 import Part2



class Test2024Day15Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/15_sample_large.txt"), "Test data file not found")
    def test_sample_large(self):
        with open("data/samples/24/15_sample_large.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 10092)

    @unittest.skipUnless(os.path.exists("data/samples/24/15_sample_small.txt"), "Test data file not found")
    def test_sample_small(self):
        with open("data/samples/24/15_sample_small.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 2028)

    @unittest.skipUnless(os.path.exists("data/full/24/15.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/15.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 1430536)


class Test2024Day15Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/15_sample_large.txt"), "Test data file not found")
    def test_sample_large(self):
        with open("data/samples/24/15_sample_large.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 9021)

    @unittest.skipUnless(os.path.exists("data/samples/24/15_sample_small.txt"), "Test data file not found")
    def test_sample_small(self):
        with open("data/samples/24/15_sample_small.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 1751)

    @unittest.skipUnless(os.path.exists("data/full/24/15.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/15.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 1452348)


if __name__ == "__main__":
    unittest.main()
