# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day06.part_1 import Part1
from aoc25.day06.part_2 import Part2


class Test2025Day06Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/06_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/06_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 4277556)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/06.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/06.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 4583860641327)


class Test2025Day06Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/06_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/06_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 3263827)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/06.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/06.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 11602774058280)


if __name__ == "__main__":
    unittest.main()
