# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day11.part_1 import Part1
from aoc25.day11.part_2 import Part2


class Test2025Day11Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/11_sample.txt")),
        "Test data file not found")
    def test_sample_part1(self):
        path = resolve_data_path("data/samples/25/11_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 5)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/11.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/11.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 640)


class Test2025Day11Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/11_sample2.txt")),
        "Test data file not found")
    def test_sample_part2(self):
        path = resolve_data_path("data/samples/25/11_sample2.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 2)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/11.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/11.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 367579641755680)


if __name__ == "__main__":
    unittest.main()
