// Code generated by testgen. DO NOT EDIT.
package day13_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day13"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/13_sample.txt", day13.Part1)
		if !ok {
			return
		}
		if result != 480 {
			t.Errorf("Expected %v, got %v", 480, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/13.txt", day13.Part1)
		if !ok {
			return
		}
		if result != 28753 {
			t.Errorf("Expected %v, got %v", 28753, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/13_sample.txt", day13.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/13.txt", day13.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/13_sample.txt", day13.Part2)
		if !ok {
			return
		}
		if result != 875318608908 {
			t.Errorf("Expected %v, got %v", 875318608908, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/13.txt", day13.Part2)
		if !ok {
			return
		}
		if result != 102718967795500 {
			t.Errorf("Expected %v, got %v", 102718967795500, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/13_sample.txt", day13.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/13.txt", day13.Part2)
	})
}
