// Code generated by testgen. DO NOT EDIT.
package day11_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc25/day11"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample_part1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/11_sample.txt", day11.Part1)
		if !ok {
			return
		}
		if result != 5 {
			t.Errorf("Expected %v, got %v", 5, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/11.txt", day11.Part1)
		if !ok {
			return
		}
		if result != 640 {
			t.Errorf("Expected %v, got %v", 640, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample_part1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/11_sample.txt", day11.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/11.txt", day11.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_part2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/11_sample2.txt", day11.Part2)
		if !ok {
			return
		}
		if result != 2 {
			t.Errorf("Expected %v, got %v", 2, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/11.txt", day11.Part2)
		if !ok {
			return
		}
		if result != 367579641755680 {
			t.Errorf("Expected %v, got %v", 367579641755680, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_part2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/11_sample2.txt", day11.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/11.txt", day11.Part2)
	})
}
