// Code generated by testgen. DO NOT EDIT.

// Fallback for IDE intellisense; the real value is set by CMake.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <gtest/gtest.h>
#include <sstream>
#include <fstream>
#include <filesystem>

#include "aoc23/day01/day01.h"

static const std::string testData = R"testgen(1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet)testgen";
static const std::string testData2 = R"testgen(two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen)testgen";

TEST(Aoc23Day01Part1, sample1) {
    std::istringstream stream(testData);
    EXPECT_EQ(aoc23::day01::Part1(stream), 142);
}

TEST(Aoc23Day01Part1, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/23/01.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc23::day01::Part1(stream), 54331);
}

TEST(Aoc23Day01Part2, sample2) {
    std::istringstream stream(testData2);
    EXPECT_EQ(aoc23::day01::Part2(stream), 281);
}

TEST(Aoc23Day01Part2, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/23/01.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc23::day01::Part2(stream), 54518);
}
