# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day07.part_1 import Part1
from aoc24.day07.part_2 import Part2



class Test2024Day07Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/07_sample.txt"), "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/07_sample.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 3749)

    @unittest.skipUnless(os.path.exists("data/full/24/07.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/07.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 3598800864292)


class Test2024Day07Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/07_sample.txt"), "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/07_sample.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 11387)

    @unittest.skipUnless(os.path.exists("data/full/24/07.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/07.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 340362529351427)


if __name__ == "__main__":
    unittest.main()
