// Code generated by testgen. DO NOT EDIT.
package day08_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day08"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/08_sample_1.txt", day08.Part1)
		if !ok {
			return
		}
		if result != 14 {
			t.Errorf("Expected %v, got %v", 14, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/08.txt", day08.Part1)
		if !ok {
			return
		}
		if result != 351 {
			t.Errorf("Expected %v, got %v", 351, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample_1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/08_sample_1.txt", day08.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/08.txt", day08.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/08_sample_1.txt", day08.Part2)
		if !ok {
			return
		}
		if result != 34 {
			t.Errorf("Expected %v, got %v", 34, result)
		}
	})

	t.Run("sample_2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/08_sample_2.txt", day08.Part2)
		if !ok {
			return
		}
		if result != 12 {
			t.Errorf("Expected %v, got %v", 12, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/08.txt", day08.Part2)
		if !ok {
			return
		}
		if result != 1259 {
			t.Errorf("Expected %v, got %v", 1259, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/08_sample_1.txt", day08.Part2)
	})

	b.Run("sample_2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/08_sample_2.txt", day08.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/08.txt", day08.Part2)
	})
}

