package day08_test

import (
	"strings"
	"testing"

	"github.com/donmahallem/aoc/aoc24/day08"
)

const testData string = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

func Test24Day08Part1(t *testing.T) {

	if result := day08.Part1(strings.NewReader(testData)); result != 14 {
		t.Errorf(`Expected %d to match %d`, result, 14)
	}
}
