# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day07.part_1 import Part1
from aoc25.day07.part_2 import Part2


class Test2025Day07Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/07_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/07_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 21)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/07.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/07.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 1658)


class Test2025Day07Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/07_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/07_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 40)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/07.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/07.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 53916299384254)


if __name__ == "__main__":
    unittest.main()
