// Code generated by testgen. DO NOT EDIT.
package day01_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day01"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet`

var testData2 = `two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen`

func TestPart1(t *testing.T) {
	t.Run("sample1", func(t *testing.T) {
		result, err := day01.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 142 {
			t.Errorf("Expected %v, got %v", 142, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/01.txt", day01.Part1)
		if !ok {
			return
		}
		if result != 54331 {
			t.Errorf("Expected %v, got %v", 54331, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample1", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day01.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/01.txt", day01.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample2", func(t *testing.T) {
		result, err := day01.Part2(strings.NewReader(testData2))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 281 {
			t.Errorf("Expected %v, got %v", 281, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/01.txt", day01.Part2)
		if !ok {
			return
		}
		if result != 54518 {
			t.Errorf("Expected %v, got %v", 54518, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample2", func(b *testing.B) {
		reader := strings.NewReader(testData2)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day01.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/01.txt", day01.Part2)
	})
}
