# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day01.part_1 import Part1
from aoc25.day01.part_2 import Part2


class Test2025Day01Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/01_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/01_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 3)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/01.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/01.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 1129)


class Test2025Day01Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/01_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/01_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 6)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/01.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/01.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 6638)


if __name__ == "__main__":
    unittest.main()
