# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day21.part_1 import Part1
from aoc24.day21.part_2 import Part2

testData = """029A
980A
179A
456A
379A"""


class Test2024Day21Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 126384)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/21.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/21.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 246990)


class Test2024Day21Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 154115708116294)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/21.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/21.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 306335137543664)


if __name__ == "__main__":
    unittest.main()
