// Code generated by testgen. DO NOT EDIT.
package day04_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day04"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/04_sample.txt", day04.Part1)
		if !ok {
			return
		}
		if result != 13 {
			t.Errorf("Expected %v, got %v", 13, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/04_sample.txt", day04.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/04_sample.txt", day04.Part2)
		if !ok {
			return
		}
		if result != 30 {
			t.Errorf("Expected %v, got %v", 30, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/04_sample.txt", day04.Part2)
	})
}
