// Code generated by testgen. DO NOT EDIT.
package day17_test

import (
	"slices"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day17"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/17_sample_1.txt", day17.Part1)
		if !ok {
			return
		}
		expected := []int{4, 6, 3, 5, 6, 3, 5, 2, 1, 0}
		if !slices.Equal(result, expected) {
			t.Errorf("Expected %v, got %v", expected, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/17.txt", day17.Part1)
		if !ok {
			return
		}
		expected := []int{6, 7, 5, 2, 1, 3, 5, 1, 7}
		if !slices.Equal(result, expected) {
			t.Errorf("Expected %v, got %v", expected, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample_1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/17_sample_1.txt", day17.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/17.txt", day17.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/17_sample_2.txt", day17.Part2)
		if !ok {
			return
		}
		if result != 117440 {
			t.Errorf("Expected %v, got %v", 117440, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/17.txt", day17.Part2)
		if !ok {
			return
		}
		if result != 216549846240877 {
			t.Errorf("Expected %v, got %v", 216549846240877, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/17_sample_2.txt", day17.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/17.txt", day17.Part2)
	})
}
