// Code generated by testgen. DO NOT EDIT.
package day18_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day18"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/18_sample.txt", day18.Part1)
		if !ok {
			return
		}
		if result != 62 {
			t.Errorf("Expected %v, got %v", 62, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/18.txt", day18.Part1)
		if !ok {
			return
		}
		if result != 31171 {
			t.Errorf("Expected %v, got %v", 31171, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/18_sample.txt", day18.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/18.txt", day18.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/18_sample.txt", day18.Part2)
		if !ok {
			return
		}
		if result != 952408144115 {
			t.Errorf("Expected %v, got %v", 952408144115, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/18.txt", day18.Part2)
		if !ok {
			return
		}
		if result != 131431655002266 {
			t.Errorf("Expected %v, got %v", 131431655002266, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/18_sample.txt", day18.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/18.txt", day18.Part2)
	})
}
