// Code generated by testgen. DO NOT EDIT.
package day20_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day20"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `broadcaster -> a, b, c
%a -> b
%b -> c
%c -> inv
&inv -> a`

var testData2 = `broadcaster -> a
%a -> inv, con
&inv -> b
%b -> con
&con -> output`

func TestPart1(t *testing.T) {
	t.Run("sample1", func(t *testing.T) {
		result, err := day20.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 32000000 {
			t.Errorf("Expected %v, got %v", 32000000, result)
		}
	})

	t.Run("sample2", func(t *testing.T) {
		result, err := day20.Part1(strings.NewReader(testData2))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 11687500 {
			t.Errorf("Expected %v, got %v", 11687500, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/20.txt", day20.Part1)
		if !ok {
			return
		}
		if result != 777666211 {
			t.Errorf("Expected %v, got %v", 777666211, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample1", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day20.Part1(reader)
		}
	})

	b.Run("sample2", func(b *testing.B) {
		reader := strings.NewReader(testData2)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day20.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/20.txt", day20.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/20.txt", day20.Part2)
		if !ok {
			return
		}
		if result != 243081086866483 {
			t.Errorf("Expected %v, got %v", 243081086866483, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/20.txt", day20.Part2)
	})
}
