// Code generated by testgen. DO NOT EDIT.
package day21_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day21"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/21_sample.txt", day21.Part1)
		if !ok {
			return
		}
		if result != 42 {
			t.Errorf("Expected %v, got %v", 42, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/21.txt", day21.Part1)
		if !ok {
			return
		}
		if result != 3697 {
			t.Errorf("Expected %v, got %v", 3697, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/21_sample.txt", day21.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/21.txt", day21.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/21_sample.txt", day21.Part2)
		if !ok {
			return
		}
		if result != 394693535848011 {
			t.Errorf("Expected %v, got %v", 394693535848011, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/21.txt", day21.Part2)
		if !ok {
			return
		}
		if result != 608152828731262 {
			t.Errorf("Expected %v, got %v", 608152828731262, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/21_sample.txt", day21.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/21.txt", day21.Part2)
	})
}
