# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day01.part_1 import Part1
from aoc24.day01.part_2 import Part2

testData = """3   4
4   3
2   5
1   3
3   9
3   3"""


class Test2024Day01Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 11)

    @unittest.skipUnless(os.path.exists("data/full/24/01.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/01.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 2057374)


class Test2024Day01Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 31)

    @unittest.skipUnless(os.path.exists("data/full/24/01.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/01.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 23177084)


if __name__ == "__main__":
    unittest.main()
