// Code generated by testgen. DO NOT EDIT.

// Fallback for build systems that set TEST_DATA_DIR at compile time.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aoc24/day03/day03.h"
static const char testData[] = "xmul(2,4)&mul[3,7]!^don't()_mul(5,5)+mul(32,64](mul(11,8)undo()?mul(8,5))";
static void test_03_part1_sample(void)
{
    FILE* in = tmpfile();
    aoc_result_t result;
    aoc_error_t err;

    assert(in != NULL);

    /* inline sample input */
    fputs(testData, in);
    rewind(in);
    err = aoc24_day03_part1(in, &result);
    assert(err == AOC_OK);
    /* scalar expected (i64) */
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 161);

    fclose(in);
}
static void test_03_part1_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/03.txt";
    FILE* f = fopen(path, "r");
    if (!f) { printf("missing %s\n", path); return; }

    aoc_result_t result;
    aoc_error_t err = aoc24_day03_part1(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 179571322);
}
static void test_03_part2_sample(void)
{
    FILE* in = tmpfile();
    aoc_result_t result;
    aoc_error_t err;

    assert(in != NULL);

    /* inline sample input */
    fputs(testData, in);
    rewind(in);
    err = aoc24_day03_part2(in, &result);
    assert(err == AOC_OK);
    /* scalar expected (i64) */
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 48);

    fclose(in);
}
static void test_03_part2_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/03.txt";
    FILE* f = fopen(path, "r");
    if (!f) { printf("missing %s\n", path); return; }

    aoc_result_t result;
    aoc_error_t err = aoc24_day03_part2(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 103811193);
}

int main(void)
{
    test_03_part1_sample();
    test_03_part1_full_data();
    test_03_part2_sample();
    test_03_part2_full_data();
    return 0;
}
