// Code generated by testgen. DO NOT EDIT.

// Fallback for build systems that set TEST_DATA_DIR at compile time.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aoc24/day04/day04.h"
static void test_04_part1_sample(void)
{
    const char *path = TEST_DATA_DIR "/data/samples/24/04_sample.txt";
    FILE *f = fopen(path, "r");
    if (!f)
    {
        printf("missing %s\n", path);
        return;
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day04_part1(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 18);
}
static void test_04_part1_full_data(void)
{
    fprintf(stderr, "Running part 1 full data...\n");
    const char *path = TEST_DATA_DIR "/data/full/24/04.txt";
    FILE *f = fopen(path, "r");
    if (!f)
    {
        printf("missing %s\n", path);
        return;
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day04_part1(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 2618);
}
static void test_04_part2_sample(void)
{
    fprintf(stderr, "Running part 2 sample data...\n");
    const char *path = TEST_DATA_DIR "/data/samples/24/04_sample.txt";
    FILE *f = fopen(path, "r");
    if (!f)
    {
        printf("missing %s\n", path);
        return;
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day04_part2(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 9);
}
static void test_04_part2_full_data(void)
{
    fprintf(stderr, "Running part 2 full data...\n");
    const char *path = TEST_DATA_DIR "/data/full/24/04.txt";
    FILE *f = fopen(path, "r");
    if (!f)
    {
        printf("missing %s\n", path);
        return;
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day04_part2(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 2011);
}

int main(void)
{
    test_04_part1_sample();
    test_04_part1_full_data();
    test_04_part2_sample();
    test_04_part2_full_data();
    return 0;
}
