// Code generated by testgen. DO NOT EDIT.

// Fallback for build systems that set TEST_DATA_DIR at compile time.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aoc24/day02/day02.h"
static const char testData[] = "7 6 4 2 1\n1 2 7 8 9\n9 7 6 2 1\n1 3 2 4 5\n8 6 4 4 1\n1 3 6 7 9";
static void test_02_part1_sample(void)
{
    FILE* in = tmpfile();
    aoc_result_t result;
    aoc_error_t err;

    assert(in != NULL);

    /* inline sample input */
    fputs(testData, in);
    rewind(in);
    err = aoc24_day02_part1(in, &result);
    assert(err == AOC_OK);
    /* scalar expected (i64) */
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 2);

    fclose(in);
}
static void test_02_part1_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/02.txt";
    FILE* f = fopen(path, "r");
    if (!f) { printf("missing %s\n", path); return; }

    aoc_result_t result;
    aoc_error_t err = aoc24_day02_part1(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 390);
}
static void test_02_part2_sample(void)
{
    FILE* in = tmpfile();
    aoc_result_t result;
    aoc_error_t err;

    assert(in != NULL);

    /* inline sample input */
    fputs(testData, in);
    rewind(in);
    err = aoc24_day02_part2(in, &result);
    assert(err == AOC_OK);
    /* scalar expected (i64) */
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 4);

    fclose(in);
}
static void test_02_part2_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/02.txt";
    FILE* f = fopen(path, "r");
    if (!f) { printf("missing %s\n", path); return; }

    aoc_result_t result;
    aoc_error_t err = aoc24_day02_part2(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 439);
}

int main(void)
{
    test_02_part1_sample();
    test_02_part1_full_data();
    test_02_part2_sample();
    test_02_part2_full_data();
    return 0;
}
