// Code generated by testgen. DO NOT EDIT.

// Fallback for build systems that set TEST_DATA_DIR at compile time.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aoc24/day01/day01.h"
static const char testData[] = "3   4\n4   3\n2   5\n1   3\n3   9\n3   3";
static void test_01_part1_sample(void)
{
    FILE* in = tmpfile();
    aoc_result_t result;
    aoc_error_t err;

    assert(in != NULL);

    /* inline sample input */
    fputs(testData, in);
    rewind(in);
    err = aoc24_day01_part1(in, &result);
    assert(err == AOC_OK);
    /* scalar expected (i64) */
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 11);

    fclose(in);
}
static void test_01_part1_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/01.txt";
    FILE* f = fopen(path, "r");
    if (!f) { printf("missing %s\n", path); return; }

    aoc_result_t result;
    aoc_error_t err = aoc24_day01_part1(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 2057374);
}
static void test_01_part2_sample(void)
{
    FILE* in = tmpfile();
    aoc_result_t result;
    aoc_error_t err;

    assert(in != NULL);

    /* inline sample input */
    fputs(testData, in);
    rewind(in);
    err = aoc24_day01_part2(in, &result);
    assert(err == AOC_OK);
    /* scalar expected (i64) */
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 31);

    fclose(in);
}
static void test_01_part2_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/01.txt";
    FILE* f = fopen(path, "r");
    if (!f) { printf("missing %s\n", path); return; }

    aoc_result_t result;
    aoc_error_t err = aoc24_day01_part2(f, &result);
    fclose(f);
    assert(err == AOC_OK);
    assert(result.kind == AOC_RESULT_I64);
    assert(result.value.i64 == 23177084);
}

int main(void)
{
    test_01_part1_sample();
    test_01_part1_full_data();
    test_01_part2_sample();
    test_01_part2_full_data();
    return 0;
}
