// Code generated by testgen. DO NOT EDIT.

// Fallback for build systems that set TEST_DATA_DIR at compile time.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include "unity.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aoc24/day05/day05.h"

void setUp(void) {}
void tearDown(void) {}
static void test_05_part1_sample(void)
{
    const char* path = TEST_DATA_DIR "/data/samples/24/05_sample.txt";
    FILE* f = fopen(path, "r");
    if (!f) {
        char msg[512];
        snprintf(msg, sizeof(msg), "missing %s", path);
        TEST_FAIL_MESSAGE(msg);
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day05_part1(f, &result);
    fclose(f);
    TEST_ASSERT_EQUAL(AOC_OK, err);
    TEST_ASSERT_EQUAL(AOC_RESULT_I64, result.kind);
    TEST_ASSERT_EQUAL_INT64(143, result.value.i64);
}
static void test_05_part1_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/05.txt";
    FILE* f = fopen(path, "r");
    if (!f) {
        char msg[512];
        snprintf(msg, sizeof(msg), "missing %s", path);
        TEST_FAIL_MESSAGE(msg);
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day05_part1(f, &result);
    fclose(f);
    TEST_ASSERT_EQUAL(AOC_OK, err);
    TEST_ASSERT_EQUAL(AOC_RESULT_I64, result.kind);
    TEST_ASSERT_EQUAL_INT64(5268, result.value.i64);
}
static void test_05_part2_sample(void)
{
    const char* path = TEST_DATA_DIR "/data/samples/24/05_sample.txt";
    FILE* f = fopen(path, "r");
    if (!f) {
        char msg[512];
        snprintf(msg, sizeof(msg), "missing %s", path);
        TEST_FAIL_MESSAGE(msg);
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day05_part2(f, &result);
    fclose(f);
    TEST_ASSERT_EQUAL(AOC_OK, err);
    TEST_ASSERT_EQUAL(AOC_RESULT_I64, result.kind);
    TEST_ASSERT_EQUAL_INT64(123, result.value.i64);
}
static void test_05_part2_full_data(void)
{
    const char* path = TEST_DATA_DIR "/data/full/24/05.txt";
    FILE* f = fopen(path, "r");
    if (!f) {
        char msg[512];
        snprintf(msg, sizeof(msg), "missing %s", path);
        TEST_FAIL_MESSAGE(msg);
    }

    aoc_result_t result;
    aoc_error_t err = aoc24_day05_part2(f, &result);
    fclose(f);
    TEST_ASSERT_EQUAL(AOC_OK, err);
    TEST_ASSERT_EQUAL(AOC_RESULT_I64, result.kind);
    TEST_ASSERT_EQUAL_INT64(5799, result.value.i64);
}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_05_part1_sample);
    RUN_TEST(test_05_part1_full_data);
    RUN_TEST(test_05_part2_sample);
    RUN_TEST(test_05_part2_full_data);

    return UNITY_END();
}