// Code generated by testgen. DO NOT EDIT.
package day03_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day03"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `xmul(2,4)&mul[3,7]!^don't()_mul(5,5)+mul(32,64](mul(11,8)undo()?mul(8,5))`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day03.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 161 {
			t.Errorf("Expected %v, got %v", 161, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/03.txt", day03.Part1)
		if !ok {
			return
		}
		if result != 179571322 {
			t.Errorf("Expected %v, got %v", 179571322, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day03.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/03.txt", day03.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day03.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 48 {
			t.Errorf("Expected %v, got %v", 48, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/03.txt", day03.Part2)
		if !ok {
			return
		}
		if result != 103811193 {
			t.Errorf("Expected %v, got %v", 103811193, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day03.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/03.txt", day03.Part2)
	})
}
