# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day11.part_1 import Part1
from aoc24.day11.part_2 import Part2

testData = """125 17"""


class Test2024Day11Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 55312)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/11.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/11.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 235850)


class Test2024Day11Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 65601038650482)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/11.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/11.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 279903140844645)


if __name__ == "__main__":
    unittest.main()
