// Code generated by testgen. DO NOT EDIT.
package day05_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day05"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/05_sample.txt", day05.Part1)
		if !ok {
			return
		}
		if result != 35 {
			t.Errorf("Expected %v, got %v", 35, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/05.txt", day05.Part1)
		if !ok {
			return
		}
		if result != 261668924 {
			t.Errorf("Expected %v, got %v", 261668924, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/05_sample.txt", day05.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/05.txt", day05.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/05_sample.txt", day05.Part2)
		if !ok {
			return
		}
		if result != 46 {
			t.Errorf("Expected %v, got %v", 46, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/05.txt", day05.Part2)
		if !ok {
			return
		}
		if result != 24261545 {
			t.Errorf("Expected %v, got %v", 24261545, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/05_sample.txt", day05.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/05.txt", day05.Part2)
	})
}
