# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day19.part_1 import Part1
from aoc24.day19.part_2 import Part2

testData = """r, wr, b, g, bwu, rb, gb, br

brwrr
bggr
gbbr
rrbgbr
ubwu
bwurrg
brgr
bbrgwb"""


class Test2024Day19Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 6)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/19.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/19.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 333)


class Test2024Day19Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 16)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/19.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/19.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 678536865274732)


if __name__ == "__main__":
    unittest.main()
