// Code generated by testgen. DO NOT EDIT.
package day02_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day02"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/02_sample.txt", day02.Part1)
		if !ok {
			return
		}
		if result != 8 {
			t.Errorf("Expected %v, got %v", 8, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/02.txt", day02.Part1)
		if !ok {
			return
		}
		if result != 2913 {
			t.Errorf("Expected %v, got %v", 2913, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/02_sample.txt", day02.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/02.txt", day02.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/02_sample.txt", day02.Part2)
		if !ok {
			return
		}
		if result != 2286 {
			t.Errorf("Expected %v, got %v", 2286, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/02.txt", day02.Part2)
		if !ok {
			return
		}
		if result != 55593 {
			t.Errorf("Expected %v, got %v", 55593, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/02_sample.txt", day02.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/02.txt", day02.Part2)
	})
}
