// Code generated by testgen. DO NOT EDIT.
package day23_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day23"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/23_sample.txt", day23.Part1)
		if !ok {
			return
		}
		if result != 94 {
			t.Errorf("Expected %v, got %v", 94, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/23.txt", day23.Part1)
		if !ok {
			return
		}
		if result != 2094 {
			t.Errorf("Expected %v, got %v", 2094, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/23_sample.txt", day23.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/23.txt", day23.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/23_sample.txt", day23.Part2)
		if !ok {
			return
		}
		if result != 154 {
			t.Errorf("Expected %v, got %v", 154, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/23.txt", day23.Part2)
		if !ok {
			return
		}
		if result != 6442 {
			t.Errorf("Expected %v, got %v", 6442, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/23_sample.txt", day23.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/23.txt", day23.Part2)
	})
}
