// Code generated by testgen. DO NOT EDIT.
package day01_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc25/day01"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/01_sample.txt", day01.Part1)
		if !ok {
			return
		}
		if result != 3 {
			t.Errorf("Expected %v, got %v", 3, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/01.txt", day01.Part1)
		if !ok {
			return
		}
		if result != 1129 {
			t.Errorf("Expected %v, got %v", 1129, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/01_sample.txt", day01.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/01.txt", day01.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/25/01_sample.txt", day01.Part2)
		if !ok {
			return
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/25/01.txt", day01.Part2)
		if !ok {
			return
		}
		if result != 6638 {
			t.Errorf("Expected %v, got %v", 6638, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/25/01_sample.txt", day01.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/25/01.txt", day01.Part2)
	})
}
