// Code generated by testgen. DO NOT EDIT.

// Fallback for IDE intellisense; the real value is set by CMake.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <gtest/gtest.h>
#include <sstream>
#include <fstream>
#include <filesystem>

#include "aoc24/day04/day04.h"


TEST(Aoc24Day04Part1, sample) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/samples/24/04_sample.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc24::day04::Part1(stream), 18);
}

TEST(Aoc24Day04Part1, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/24/04.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc24::day04::Part1(stream), 2618);
}

TEST(Aoc24Day04Part2, sample) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/samples/24/04_sample.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc24::day04::Part2(stream), 9);
}

TEST(Aoc24Day04Part2, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/24/04.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc24::day04::Part2(stream), 2011);
}
