# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day23.part_1 import Part1
from aoc24.day23.part_2 import Part2


class Test2024Day23Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/23_sample.txt"),
                         "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/23_sample.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 7)

    @unittest.skipUnless(os.path.exists("data/full/24/23.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/23.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 926)


class Test2024Day23Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/samples/24/23_sample.txt"),
                         "Test data file not found")
    def test_sample(self):
        with open("data/samples/24/23_sample.txt") as f:
            result = Part2(f)
            self.assertEqual(result, "co,de,ka,ta")

    @unittest.skipUnless(os.path.exists("data/full/24/23.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/23.txt") as f:
            result = Part2(f)
            self.assertEqual(result, "az,ed,hz,it,ld,nh,pc,td,ty,ux,wc,yg,zz")


if __name__ == "__main__":
    unittest.main()
