# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day23.part_1 import Part1
from aoc24.day23.part_2 import Part2


class Test2024Day23Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/23_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/24/23_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 7)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/23.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/23.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 926)


class Test2024Day23Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/23_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/24/23_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, ["co", "de", "ka", "ta"])

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/23.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/23.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, [
                "az", "ed", "hz", "it", "ld", "nh", "pc", "td", "ty", "ux",
                "wc", "yg", "zz"
            ])


if __name__ == "__main__":
    unittest.main()
