// Code generated by testgen. DO NOT EDIT.
package day09_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day09"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `2333133121414131402`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day09.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 1928 {
			t.Errorf("Expected %v, got %v", 1928, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/09.txt", day09.Part1)
		if !ok {
			return
		}
		if result != 6435922584968 {
			t.Errorf("Expected %v, got %v", 6435922584968, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day09.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/09.txt", day09.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day09.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 2858 {
			t.Errorf("Expected %v, got %v", 2858, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/09.txt", day09.Part2)
		if !ok {
			return
		}
		if result != 6469636832766 {
			t.Errorf("Expected %v, got %v", 6469636832766, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day09.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/09.txt", day09.Part2)
	})
}
