// Code generated by testgen. DO NOT EDIT.
package day21_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day21"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `029A
980A
179A
456A
379A`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day21.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 126384 {
			t.Errorf("Expected %v, got %v", 126384, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/21.txt", day21.Part1)
		if !ok {
			return
		}
		if result != 246990 {
			t.Errorf("Expected %v, got %v", 246990, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day21.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/21.txt", day21.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day21.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 154115708116294 {
			t.Errorf("Expected %v, got %v", 154115708116294, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/21.txt", day21.Part2)
		if !ok {
			return
		}
		if result != 306335137543664 {
			t.Errorf("Expected %v, got %v", 306335137543664, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day21.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/21.txt", day21.Part2)
	})
}

