# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day02.part_1 import Part1
from aoc24.day02.part_2 import Part2

testData = """7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9"""


class Test2024Day02Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 2)

    @unittest.skipUnless(os.path.exists("data/full/24/02.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/02.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 390)


class Test2024Day02Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 4)

    @unittest.skipUnless(os.path.exists("data/full/24/02.txt"),
                         "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/02.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 439)


if __name__ == "__main__":
    unittest.main()
