# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day05.part_1 import Part1
from aoc25.day05.part_2 import Part2


class Test2025Day05Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/05_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/05_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 3)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/05.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/05.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 509)


class Test2025Day05Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/05_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/05_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 14)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/05.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/05.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 336790092076620)


if __name__ == "__main__":
    unittest.main()
