# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day20.part_1 import Part1
from aoc24.day20.part_2 import Part2


class Test2024Day20Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/20_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/24/20_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 0)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/20.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/20.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 1417)


class Test2024Day20Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/24/20_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/24/20_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 0)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/20.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/20.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 1014683)


if __name__ == "__main__":
    unittest.main()
