# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc24.day18.part_1 import Part1
from aoc24.day18.part_2 import Part2


class Test2024Day18Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/18.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/18.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 370)


class Test2024Day18Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/24/18.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/24/18.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, [65, 6])


if __name__ == "__main__":
    unittest.main()
