# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day18.part_1 import Part1
from aoc24.day18.part_2 import Part2



class Test2024Day18Part01(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/full/24/18.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/18.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 370)


class Test2024Day18Part02(unittest.TestCase):

    @unittest.skipUnless(os.path.exists("data/full/24/18.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/18.txt") as f:
            result = Part2(f)
            self.assertEqual(result, "65,6")


if __name__ == "__main__":
    unittest.main()
