// Code generated by testgen. DO NOT EDIT.

// Fallback for IDE intellisense; the real value is set by CMake.
#ifndef TEST_DATA_DIR
#define TEST_DATA_DIR ""
#endif

#include <gtest/gtest.h>
#include <sstream>
#include <fstream>
#include <filesystem>

#include "aoc24/day02/day02.h"

static const std::string testData = R"testgen(7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9)testgen";

TEST(Aoc24Day02Part1, sample) {
    std::istringstream stream(testData);
    EXPECT_EQ(aoc24::day02::Part1(stream), 2);
}

TEST(Aoc24Day02Part1, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/24/02.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc24::day02::Part1(stream), 390);
}

TEST(Aoc24Day02Part2, sample) {
    std::istringstream stream(testData);
    EXPECT_EQ(aoc24::day02::Part2(stream), 4);
}

TEST(Aoc24Day02Part2, full_data) {
    const std::string path = std::string(TEST_DATA_DIR) + "/data/full/24/02.txt";
    if (!std::filesystem::exists(path)) { GTEST_SKIP() << "missing " << path; }
    std::ifstream stream(path);
    EXPECT_EQ(aoc24::day02::Part2(stream), 439);
}
