// Code generated by testgen. DO NOT EDIT.
package day19_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day19"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `r, wr, b, g, bwu, rb, gb, br

brwrr
bggr
gbbr
rrbgbr
ubwu
bwurrg
brgr
bbrgwb`

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day19.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/19.txt", day19.Part1)
		if !ok {
			return
		}
		if result != 333 {
			t.Errorf("Expected %v, got %v", 333, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day19.Part1(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/19.txt", day19.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, err := day19.Part2(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 16 {
			t.Errorf("Expected %v, got %v", 16, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/19.txt", day19.Part2)
		if !ok {
			return
		}
		if result != 678536865274732 {
			t.Errorf("Expected %v, got %v", 678536865274732, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day19.Part2(reader)
		}
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/19.txt", day19.Part2)
	})
}
