// Code generated by testgen. DO NOT EDIT.
package day20_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day20"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/20_sample.txt", day20.Part1)
		if !ok {
			return
		}
		if result != 0 {
			t.Errorf("Expected %v, got %v", 0, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/20.txt", day20.Part1)
		if !ok {
			return
		}
		if result != 1417 {
			t.Errorf("Expected %v, got %v", 1417, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/20_sample.txt", day20.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/20.txt", day20.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/20_sample.txt", day20.Part2)
		if !ok {
			return
		}
		if result != 0 {
			t.Errorf("Expected %v, got %v", 0, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/20.txt", day20.Part2)
		if !ok {
			return
		}
		if result != 1014683 {
			t.Errorf("Expected %v, got %v", 1014683, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/20_sample.txt", day20.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/20.txt", day20.Part2)
	})
}
