// Code generated by testgen. DO NOT EDIT.
package day13_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day13"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/13_sample.txt", day13.Part1)
		if !ok {
			return
		}
		if result != 405 {
			t.Errorf("Expected %v, got %v", 405, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/13.txt", day13.Part1)
		if !ok {
			return
		}
		if result != 42974 {
			t.Errorf("Expected %v, got %v", 42974, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/13_sample.txt", day13.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/13.txt", day13.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/13_sample.txt", day13.Part2)
		if !ok {
			return
		}
		if result != 400 {
			t.Errorf("Expected %v, got %v", 400, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/13.txt", day13.Part2)
		if !ok {
			return
		}
		if result != 27587 {
			t.Errorf("Expected %v, got %v", 27587, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/13_sample.txt", day13.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/13.txt", day13.Part2)
	})
}
