// Code generated by testgen. DO NOT EDIT.
package day19_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day19"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/19_sample.txt", day19.Part1)
		if !ok {
			return
		}
		if result != 19114 {
			t.Errorf("Expected %v, got %v", 19114, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/19.txt", day19.Part1)
		if !ok {
			return
		}
		if result != 319295 {
			t.Errorf("Expected %v, got %v", 319295, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/19_sample.txt", day19.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/19.txt", day19.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/19_sample.txt", day19.Part2)
		if !ok {
			return
		}
		if result != 167409079868000 {
			t.Errorf("Expected %v, got %v", 167409079868000, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/19.txt", day19.Part2)
		if !ok {
			return
		}
		if result != 110807725108076 {
			t.Errorf("Expected %v, got %v", 110807725108076, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/19_sample.txt", day19.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/19.txt", day19.Part2)
	})
}
