// Code generated by testgen. DO NOT EDIT.
package day08_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day08"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/08_sample1.txt", day08.Part1)
		if !ok {
			return
		}
		if result != 2 {
			t.Errorf("Expected %v, got %v", 2, result)
		}
	})

	t.Run("sample2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/08_sample2.txt", day08.Part1)
		if !ok {
			return
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/08.txt", day08.Part1)
		if !ok {
			return
		}
		if result != 16531 {
			t.Errorf("Expected %v, got %v", 16531, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/08_sample1.txt", day08.Part1)
	})

	b.Run("sample2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/08_sample2.txt", day08.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/08.txt", day08.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample3", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/08_sample3.txt", day08.Part2)
		if !ok {
			return
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/23/08.txt", day08.Part2)
		if !ok {
			return
		}
		if result != 24035773251517 {
			t.Errorf("Expected %v, got %v", 24035773251517, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample3", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/08_sample3.txt", day08.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/23/08.txt", day08.Part2)
	})
}
