// Code generated by testgen. DO NOT EDIT.
package day08_test

import (
	"io"
	"strings"
	"testing"

	"github.com/donmahallem/aoc/go/aoc23/day08"
	"github.com/donmahallem/aoc/go/test_utils"
)

var testData = `LLR

AAA = (BBB, BBB)
BBB = (AAA, ZZZ)
ZZZ = (ZZZ, ZZZ)`

var testData2 = `LR

11A = (11B, XXX)
11B = (XXX, 11Z)
11Z = (11B, XXX)
22A = (22B, XXX)
22B = (22C, 22C)
22C = (22Z, 22Z)
22Z = (22B, 22B)
XXX = (XXX, XXX)`

func TestPart1(t *testing.T) {
	t.Run("sample2", func(t *testing.T) {
		result, err := day08.Part1(strings.NewReader(testData))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})

	t.Run("sample1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/23/08_sample1.txt", day08.Part1)
		if !ok {
			return
		}
		if result != 2 {
			t.Errorf("Expected %v, got %v", 2, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample2", func(b *testing.B) {
		reader := strings.NewReader(testData)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day08.Part1(reader)
		}
	})

	b.Run("sample1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/23/08_sample1.txt", day08.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_part2", func(t *testing.T) {
		result, err := day08.Part2(strings.NewReader(testData2))
		if err != nil {
			t.Fatalf("Unexpected error: %v", err)
		}
		if result != 6 {
			t.Errorf("Expected %v, got %v", 6, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_part2", func(b *testing.B) {
		reader := strings.NewReader(testData2)
		for b.Loop() {
			reader.Seek(0, io.SeekStart)
			day08.Part2(reader)
		}
	})
}
