// Code generated by testgen. DO NOT EDIT.
package day16_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day16"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/16_sample_1.txt", day16.Part1)
		if !ok {
			return
		}
		if result != 7036 {
			t.Errorf("Expected %v, got %v", 7036, result)
		}
	})

	t.Run("sample_2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/16_sample_2.txt", day16.Part1)
		if !ok {
			return
		}
		if result != 11048 {
			t.Errorf("Expected %v, got %v", 11048, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/16.txt", day16.Part1)
		if !ok {
			return
		}
		if result != 105508 {
			t.Errorf("Expected %v, got %v", 105508, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample_1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/16_sample_1.txt", day16.Part1)
	})

	b.Run("sample_2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/16_sample_2.txt", day16.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/16.txt", day16.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/16_sample_1.txt", day16.Part2)
		if !ok {
			return
		}
		if result != 45 {
			t.Errorf("Expected %v, got %v", 45, result)
		}
	})

	t.Run("sample_2", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/16_sample_2.txt", day16.Part2)
		if !ok {
			return
		}
		if result != 64 {
			t.Errorf("Expected %v, got %v", 64, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/16.txt", day16.Part2)
		if !ok {
			return
		}
		if result != 548 {
			t.Errorf("Expected %v, got %v", 548, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample_1", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/16_sample_1.txt", day16.Part2)
	})

	b.Run("sample_2", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/16_sample_2.txt", day16.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/16.txt", day16.Part2)
	})
}

