// Code generated by testgen. DO NOT EDIT.
package day07_test

import (
	"testing"

	"github.com/donmahallem/aoc/go/aoc24/day07"
	"github.com/donmahallem/aoc/go/test_utils"
)

func TestPart1(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/07_sample.txt", day07.Part1)
		if !ok {
			return
		}
		if result != 3749 {
			t.Errorf("Expected %v, got %v", 3749, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/07.txt", day07.Part1)
		if !ok {
			return
		}
		if result != 3598800864292 {
			t.Errorf("Expected %v, got %v", 3598800864292, result)
		}
	})
}

func BenchmarkPart1(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/07_sample.txt", day07.Part1)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/07.txt", day07.Part1)
	})
}

func TestPart2(t *testing.T) {
	t.Run("sample", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/samples/24/07_sample.txt", day07.Part2)
		if !ok {
			return
		}
		if result != 11387 {
			t.Errorf("Expected %v, got %v", 11387, result)
		}
	})

	t.Run("full_data", func(t *testing.T) {
		result, ok := test_utils.TestPartFromPath(t, "data/full/24/07.txt", day07.Part2)
		if !ok {
			return
		}
		if result != 340362529351427 {
			t.Errorf("Expected %v, got %v", 340362529351427, result)
		}
	})
}

func BenchmarkPart2(b *testing.B) {
	b.Run("sample", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/samples/24/07_sample.txt", day07.Part2)
	})

	b.Run("full_data", func(b *testing.B) {
		test_utils.BenchmarkPartFromPath(b, "data/full/24/07.txt", day07.Part2)
	})
}

