name: Black Python
on: [push]
jobs:
  linter_name:
    name: runner/black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check those fine sneks out
      - name: Run Black
        uses: psf/black@25.1.0
        with:
          options: "--check --verbose"
