name: Test Go
on: [push]

jobs:
  build:
    name: Run and Test GO
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v main.go
      - name: Test with the Go CLI
        run: go test ./...
