# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from aoc24.day03.part_1 import Part1
from aoc24.day03.part_2 import Part2

testData = """xmul(2,4)&mul[3,7]!^don't()_mul(5,5)+mul(32,64](mul(11,8)undo()?mul(8,5))"""


class Test2024Day03Part01(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part1(f)
            self.assertEqual(result, 161)

    @unittest.skipUnless(os.path.exists("data/full/24/03.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/03.txt") as f:
            result = Part1(f)
            self.assertEqual(result, 179571322)


class Test2024Day03Part02(unittest.TestCase):

    def test_sample(self):
        with io.StringIO() as f:
            f.write(testData)
            f.seek(0)
            result = Part2(f)
            self.assertEqual(result, 48)

    @unittest.skipUnless(os.path.exists("data/full/24/03.txt"), "Test data file not found")
    def test_full_data(self):
        with open("data/full/24/03.txt") as f:
            result = Part2(f)
            self.assertEqual(result, 103811193)


if __name__ == "__main__":
    unittest.main()
