# Code generated by testgen. DO NOT EDIT.
import unittest
import io
import os
from test_utils import resolve_data_path
from aoc25.day04.part_1 import Part1
from aoc25.day04.part_2 import Part2


class Test2025Day04Part01(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/04_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/04_sample.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 13)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/04.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/04.txt")
        with open(path) as f:
            result = Part1(f)
            self.assertEqual(result, 1460)


class Test2025Day04Part02(unittest.TestCase):

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/samples/25/04_sample.txt")),
        "Test data file not found")
    def test_sample(self):
        path = resolve_data_path("data/samples/25/04_sample.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 43)

    @unittest.skipUnless(
        os.path.exists(resolve_data_path("data/full/25/04.txt")),
        "Test data file not found")
    def test_full_data(self):
        path = resolve_data_path("data/full/25/04.txt")
        with open(path) as f:
            result = Part2(f)
            self.assertEqual(result, 9243)


if __name__ == "__main__":
    unittest.main()
